/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basedatos;

import com.mysql.jdbc.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author migle
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        visualizar("");
        this.jLabel1.setIcon(new ImageIcon("src\\icono.jpeg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelDorsal = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApell = new javax.swing.JLabel();
        jLabelDemar = new javax.swing.JLabel();
        TFieldDorsal = new javax.swing.JTextField();
        TFieldNombre = new javax.swing.JTextField();
        TFieldApell = new javax.swing.JTextField();
        TFieldDemar = new javax.swing.JTextField();
        BLimpiar = new javax.swing.JButton();
        BAdd = new javax.swing.JButton();
        BConsultar = new javax.swing.JButton();
        BConexion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BModificar = new javax.swing.JButton();
        BActualiz = new javax.swing.JButton();
        BDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RCCV");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabelDorsal.setBackground(new java.awt.Color(51, 153, 255));
        jLabelDorsal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelDorsal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDorsal.setText("DORSAL");

        jLabelNombre.setBackground(new java.awt.Color(51, 153, 255));
        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("NOMBRE");

        jLabelApell.setBackground(new java.awt.Color(51, 153, 255));
        jLabelApell.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelApell.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApell.setText("APELLIDO");

        jLabelDemar.setBackground(new java.awt.Color(51, 153, 255));
        jLabelDemar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelDemar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDemar.setText("DEMARCACION");

        TFieldDorsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFieldDorsalActionPerformed(evt);
            }
        });

        BLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BLimpiar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BLimpiar.setForeground(new java.awt.Color(51, 204, 255));
        BLimpiar.setText("LIMPIAR");
        BLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarActionPerformed(evt);
            }
        });

        BAdd.setBackground(new java.awt.Color(255, 255, 255));
        BAdd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BAdd.setForeground(new java.awt.Color(51, 204, 255));
        BAdd.setText("AÑADIR");
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });

        BConsultar.setBackground(new java.awt.Color(255, 255, 255));
        BConsultar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BConsultar.setForeground(new java.awt.Color(51, 204, 255));
        BConsultar.setText("CONSULTAR");
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });

        BConexion.setBackground(new java.awt.Color(255, 255, 255));
        BConexion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BConexion.setForeground(new java.awt.Color(51, 204, 255));
        BConexion.setText("Conexion BD");
        BConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConexionActionPerformed(evt);
            }
        });

        jTable1.setForeground(new java.awt.Color(51, 153, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BModificar.setBackground(new java.awt.Color(255, 255, 255));
        BModificar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BModificar.setForeground(new java.awt.Color(51, 204, 255));
        BModificar.setText("MODIFICAR");
        BModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModificarActionPerformed(evt);
            }
        });

        BActualiz.setBackground(new java.awt.Color(255, 255, 255));
        BActualiz.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BActualiz.setForeground(new java.awt.Color(51, 204, 255));
        BActualiz.setText("UPDATE");
        BActualiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizActionPerformed(evt);
            }
        });

        BDelete.setBackground(new java.awt.Color(255, 255, 255));
        BDelete.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BDelete.setForeground(new java.awt.Color(51, 204, 255));
        BDelete.setText("ELIMINAR");
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDorsal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelApell, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDemar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TFieldDorsal)
                                .addComponent(TFieldNombre)
                                .addComponent(TFieldDemar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(TFieldApell))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BActualiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApell, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldApell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDemar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldDemar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BActualiz, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void visualizar(String valor){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("DORSAL");
        model.addColumn("NOMBRE");
        model.addColumn("APELLIDO");
        model.addColumn("DEMARCACION");
        jTable1.setModel(model);
            Connection con = uhum.conexion();
            String [] jugadores = new String[4];
            String sql="";
            if(valor.equals("")){
                sql="select * from celpla";
            }
            else
                sql="select * from celpla where dorsal='"+valor+"'";
        try {
            java.sql.Statement sta = con.createStatement();
            ResultSet res = sta.executeQuery(sql);
            while(res.next()){
                jugadores[0] = res.getString(1);
                jugadores[1] = res.getString(2);
                jugadores[2] = res.getString(3);
                jugadores[3] = res.getString(4);
                model.addRow(jugadores);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    Metodos uhum = new Metodos();
    private void TFieldDorsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFieldDorsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFieldDorsalActionPerformed

    private void BLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarActionPerformed
        TFieldDorsal.setText("");
        TFieldNombre.setText("");
        TFieldApell.setText("");
        TFieldDemar.setText("");
    }//GEN-LAST:event_BLimpiarActionPerformed

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddActionPerformed
        Metodos con = new Metodos();
        Connection re = con.conexion();
        String dorsal, nombre, apell, demarc;
        String sql;
        
        dorsal = TFieldDorsal.getText();
        nombre = TFieldNombre.getText();
        apell = TFieldApell.getText();
        demarc = TFieldDemar.getText();
        
        sql = "INSERT INTO celpla (Dorsal,Nombre,Apellido,Demarcacion) VALUES (?,?,?,?)";
        try {
            PreparedStatement prepsta =  re.prepareStatement(sql);
            prepsta.setString(1, dorsal);
            prepsta.setString(2, nombre);
            prepsta.setString(3, apell);
            prepsta.setString(4, demarc);
            int n = prepsta.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(this, "Insercion realizada");
            }
            
            else
                JOptionPane.showMessageDialog(this, "Error en la insercion");
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{TFieldDorsal.getText(), TFieldNombre.getText(), TFieldApell.getText(),TFieldDemar.getText()});
            
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BAddActionPerformed

    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed
        ResultSet resul = null;
        Statement stat = null;
        String sql = JOptionPane.showInputDialog("Introduce la consulta");
        try {
            stat = (Statement) uhum.conexion().createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            resul = stat.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        String visualiz ="DORSAL NOMBRE  APELLIDO   DEMARCACION \n-----------------------------------------------------------------\n";        
        try {
            while (resul.next()) {
                visualiz = visualiz +"  "+ resul.getBigDecimal("Dorsal")+"               "+resul.getString("Nombre")+"            "+resul.getString("Apellido")+"          "+resul.getString("Demarcacion")+"\n" ;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
                JOptionPane.showMessageDialog(this, visualiz);
        
        
    }//GEN-LAST:event_BConsultarActionPerformed

    private void BConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConexionActionPerformed
        uhum.conexion();
    }//GEN-LAST:event_BConexionActionPerformed

    private void BModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModificarActionPerformed
        int fila = jTable1.getSelectedRow();
        if(fila>=0){
            TFieldDorsal.setText(jTable1.getValueAt(fila, 0).toString());
            TFieldNombre.setText(jTable1.getValueAt(fila, 1).toString());
            TFieldApell.setText(jTable1.getValueAt(fila, 2).toString());
            TFieldDemar.setText(jTable1.getValueAt(fila, 3).toString());
        }
        else
            JOptionPane.showMessageDialog(this, "Elige una fila");
    }//GEN-LAST:event_BModificarActionPerformed

    private void BActualizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizActionPerformed
        try {
            PreparedStatement prep = uhum.conexion().prepareStatement("update celpla set Nombre='"+TFieldNombre.getText()+"',Apellido='"+TFieldApell.getText()+"',Demarcacion='"+TFieldDemar.getText()+"' where Dorsal='"+TFieldDorsal.getText()+"'");
            prep.execute();
            visualizar("");
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BActualizActionPerformed

    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        int filaselecc = jTable1.getSelectedRow();
        String dorsal=""+jTable1.getValueAt(filaselecc, 0).toString();
        try {
            PreparedStatement prep = uhum.conexion().prepareStatement("delete from celpla where Dorsal='"+dorsal+"'");
            prep.executeUpdate();
            visualizar("");
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualiz;
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BConexion;
    private javax.swing.JButton BConsultar;
    private javax.swing.JButton BDelete;
    private javax.swing.JButton BLimpiar;
    private javax.swing.JButton BModificar;
    private javax.swing.JTextField TFieldApell;
    private javax.swing.JTextField TFieldDemar;
    private javax.swing.JTextField TFieldDorsal;
    private javax.swing.JTextField TFieldNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApell;
    private javax.swing.JLabel jLabelDemar;
    private javax.swing.JLabel jLabelDorsal;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
