/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package basedatos;

import com.mysql.jdbc.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author migle
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.jLabel1.setIcon(new ImageIcon("src\\icono.jpeg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelDorsal = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApell = new javax.swing.JLabel();
        jLabelDemar = new javax.swing.JLabel();
        TFieldDorsal = new javax.swing.JTextField();
        TFieldNombre = new javax.swing.JTextField();
        TFieldApell = new javax.swing.JTextField();
        TFieldDemar = new javax.swing.JTextField();
        BLimpiar = new javax.swing.JButton();
        BAdd = new javax.swing.JButton();
        BConsultar = new javax.swing.JButton();
        BConexion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RCCV");

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabelDorsal.setBackground(new java.awt.Color(51, 153, 255));
        jLabelDorsal.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelDorsal.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDorsal.setText("DORSAL");

        jLabelNombre.setBackground(new java.awt.Color(51, 153, 255));
        jLabelNombre.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("NOMBRE");

        jLabelApell.setBackground(new java.awt.Color(51, 153, 255));
        jLabelApell.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelApell.setForeground(new java.awt.Color(255, 255, 255));
        jLabelApell.setText("APELLIDO");

        jLabelDemar.setBackground(new java.awt.Color(51, 153, 255));
        jLabelDemar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelDemar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDemar.setText("DEMARCACION");

        TFieldDorsal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFieldDorsalActionPerformed(evt);
            }
        });

        BLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BLimpiar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BLimpiar.setForeground(new java.awt.Color(51, 204, 255));
        BLimpiar.setText("LIMPIAR");
        BLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BLimpiarActionPerformed(evt);
            }
        });

        BAdd.setBackground(new java.awt.Color(255, 255, 255));
        BAdd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BAdd.setForeground(new java.awt.Color(51, 204, 255));
        BAdd.setText("AÑADIR");
        BAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAddActionPerformed(evt);
            }
        });

        BConsultar.setBackground(new java.awt.Color(255, 255, 255));
        BConsultar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        BConsultar.setForeground(new java.awt.Color(51, 204, 255));
        BConsultar.setText("CONSULTAR");
        BConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConsultarActionPerformed(evt);
            }
        });

        BConexion.setBackground(new java.awt.Color(255, 255, 255));
        BConexion.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        BConexion.setForeground(new java.awt.Color(51, 204, 255));
        BConexion.setText("Conexion BD");
        BConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BConexionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDorsal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelApell, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelDemar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TFieldDorsal)
                                .addComponent(TFieldNombre)
                                .addComponent(TFieldDemar, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(TFieldApell))
                            .addComponent(BLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(BConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApell, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldApell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDemar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFieldDemar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    Metodos uhum = new Metodos();
    private void TFieldDorsalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFieldDorsalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFieldDorsalActionPerformed

    private void BLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BLimpiarActionPerformed
        TFieldDorsal.setText("");
        TFieldNombre.setText("");
        TFieldApell.setText("");
        TFieldDemar.setText("");
    }//GEN-LAST:event_BLimpiarActionPerformed

    private void BAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAddActionPerformed
        Metodos con = new Metodos();
        Connection re = con.conexion();
        String dorsal, nombre, apell, demarc;
        String sql;
        
        dorsal = TFieldDorsal.getText();
        nombre = TFieldNombre.getText();
        apell = TFieldApell.getText();
        demarc = TFieldDemar.getText();
        
        sql = "INSERT INTO celpla (Dorsal,Nombre,Apellido,Demarcacion) VALUES (?,?,?,?)";
        try {
            PreparedStatement prepsta =  re.prepareStatement(sql);
            prepsta.setString(1, dorsal);
            prepsta.setString(2, nombre);
            prepsta.setString(3, apell);
            prepsta.setString(4, demarc);
            int n = prepsta.executeUpdate();
            if(n>0){
                JOptionPane.showMessageDialog(this, "Insercion realizada");
            }
            else
                JOptionPane.showMessageDialog(this, "Error en la insercion");
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BAddActionPerformed

    private void BConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConsultarActionPerformed
        ResultSet resul = null;
        Statement stat = null;
        String sql = JOptionPane.showInputDialog("Introduce la consulta");
        try {
            stat = (Statement) uhum.conexion().createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            resul = stat.executeQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String visualiz ="DORSAL NOMBRE  APELLIDO   DEMARCACION \n-----------------------------------------------------------------\n";
                
        try {
            while (resul.next()) {
                visualiz = visualiz +"  "+ resul.getBigDecimal("Dorsal")+"               "+resul.getString("Nombre")+"            "+resul.getString("Apellido")+"          "+resul.getString("Demarcacion")+"\n" ;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
                JOptionPane.showMessageDialog(this, visualiz);
        
        
    }//GEN-LAST:event_BConsultarActionPerformed

    private void BConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BConexionActionPerformed
        uhum.conexion();
    }//GEN-LAST:event_BConexionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAdd;
    private javax.swing.JButton BConexion;
    private javax.swing.JButton BConsultar;
    private javax.swing.JButton BLimpiar;
    private javax.swing.JTextField TFieldApell;
    private javax.swing.JTextField TFieldDemar;
    private javax.swing.JTextField TFieldDorsal;
    private javax.swing.JTextField TFieldNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApell;
    private javax.swing.JLabel jLabelDemar;
    private javax.swing.JLabel jLabelDorsal;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
